// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ListPageInput struct {
	Page  int    `json:"page"`
	Limit int    `json:"limit"`
	Sort  string `json:"sort"`
}

type Mutation struct {
}

type Order struct {
	ID          string  `json:"ID"`
	ProductName string  `json:"ProductName"`
	Price       float64 `json:"Price"`
	Tax         float64 `json:"Tax"`
	FinalPrice  float64 `json:"FinalPrice"`
}

type OrderInput struct {
	ProductName string  `json:"ProductName"`
	Price       float64 `json:"Price"`
	Tax         float64 `json:"Tax"`
}

type Query struct {
}
